{{- if .Values.freshclamConfig -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}-freshclam
  labels:
    app: {{ .Release.Namespace }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  freshclam.conf:
    {{ toYaml .Values.freshclamConfig | indent 4 }}
{{- end }}
